#!/bin/sh
set -e

if [ ! -d app-doc ]; then
	>&2 echo 'Wrong folder.'
	exit 1
fi

for PN in execline s6 s6-rc s6-portable-utils s6-linux-init tipidee; do
	PN="$PN-man-pages"
	read -r PV <<EOF
$(curl -Ls "https://git.sr.ht/~flexibeast/${PN}/refs/rss.xml" |
	python -c 'import xml.etree.ElementTree as ET; print(ET.parse(0).getroot().find("channel").find("item").find("title").text.strip("v \t"))')
EOF
	OUT="app-doc/${PN}/${PN:?}-${PV:?}.ebuild"
	if [ -f "$OUT" ]; then
		>&2 printf '%s already exists.\n' "$OUT"
		continue
	fi

	if install -Dm644 /dev/stdin "$OUT" <<EOF && ebuild "$OUT" digest
# Copyright $(date +%Y) Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DESCRIPTION="mdoc versions of the documentation for the ${PN%-man-pages} suite"
HOMEPAGE="https://git.sr.ht/~flexibeast/$PN"
SRC_URI="https://git.sr.ht/~flexibeast/\$PN/archive/v\$PV.tar.gz -> \$P.tar.gz"

LICENSE="ISC"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND="\${DEPEND}"
BDEPEND=""
S="\${WORKDIR}/\${PN}-v\${PV}"

src_install() {
	make MAN_DIR="\$D/usr/share/man" install
}
EOF
	then
		printf 'Generated %s.\n' "$OUT"
	else
		rm -f -- "$OUT"
		printf 'Generating %s failed.\n' "$OUT"
	fi
done
